{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3fb62ec7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Are you ready to play Quiz Game? yes\n",
      "Please Give Your Name: Ridoy\n",
      "Please Give Your Mobile Number: 01983274785\n",
      "please Give Your Date of Birth: like dd/mm/yy 20-06-1999\n",
      "\n",
      "========================================================= Thank You =========================================================\n",
      "\n",
      "    Your Name is:          Ridoy\n",
      "    Your Mobile Number is: 01983274785\n",
      "    Your Date of Birth is: 20-06-1999     \n",
      "        \n",
      "is everything correct? yes\n",
      "Creating your Gameing ID ......................................................................................................\n",
      "\n",
      "Your Quiz Gameing ID is: R182481999\n",
      "\n",
      "===================================================== Let's start the Game ====================================================\n",
      "\n",
      "\n",
      "    Please Select the Subject 🙂\n",
      "\n",
      "    1. Science\n",
      "    2. Robotics\n",
      "    3. Math\n",
      "    4. Computer\n",
      "    5. Sports\n",
      "                \n",
      "please choose one: 2\n",
      "\n",
      "=============================================== Thank you for selected Roborics ===============================================\n",
      "Loading your question paper....................................................................................................1. What is the full meaning of IR sensor?\n",
      "    a) infrared\n",
      "    b) infrared light\n",
      "    c) international radio\n",
      "    d) internet refollow\n",
      "    a\n",
      "You selected = a\n",
      "2. What is the full meaning of PIR sensor?\n",
      "    a) positive infrared\n",
      "    b) point of infrared\n",
      "    c) Passive infrared\n",
      "    d) plus infrared \n",
      "    c\n",
      "You selected = c\n",
      "3. What is the full meaning of RF?\n",
      "    a) Radio frequency\n",
      "    b) Radio free\n",
      "    c) Radio fall\n",
      "    d) Radio following\n",
      "    a\n",
      "You selected = a\n",
      "4. What is the full meaning of AI?\n",
      "    a) Artificial internet\n",
      "    b) Artificial information\n",
      "    c) Artificial interface\n",
      "    d) Artificial intelligence\n",
      "    a\n",
      "You selected = a\n",
      "5. what is the name of world best robot?\n",
      "    a) Reco            \n",
      "    b) Sophia\n",
      "    c) Roba\n",
      "    d) Seba\n",
      "    b\n",
      "You selected = b\n",
      "\n",
      "Congratulations 🙂\n",
      "you gave 80 % correct answers & 20 % wrong answers\n",
      "are you want to see which question you gave the wrong answer to? yes\n",
      "4. What is the full meaning of AI?\n",
      "    a) Artificial internet\n",
      "    b) Artificial information\n",
      "    c) Artificial interface\n",
      "    d) Artificial intelligence\n",
      "\n",
      "    Correct ans is:- d)Artificial intelligence\n",
      "    you gave: a\n",
      "    \n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename = \"Quiz_game.log\", level = logging.DEBUG, format = (\"%(asctime)s %(levelname)s %(message)s\"))\n",
    "\n",
    "\n",
    "# Make function for loading \n",
    "def sleep_time():\n",
    "    print(\"Loading your question paper\", end=\"\")\n",
    "    a = 0\n",
    "    while a<100:\n",
    "        print(\".\", end=\"\")\n",
    "        time.sleep(0.05)\n",
    "        a+=1\n",
    "    return \" \"\n",
    "try:\n",
    "    # for make a result\n",
    "    ok = 0\n",
    "    ng = 0\n",
    "    wrong = []\n",
    "\n",
    "    # check you are intersted or not\n",
    "    ans = input(\"Are you ready to play Quiz Game? \").lower()\n",
    "\n",
    "    if ans != \"yes\":\n",
    "        print(\"Thank You\")\n",
    "        logging.info(\"user aren't ready to play Quiz Game\")\n",
    "        pass\n",
    "    # take user information\n",
    "    else:\n",
    "        logging.info(\"user ready to play\")\n",
    "        name_list = []\n",
    "        name = input(\"Please Give Your Name: \")\n",
    "        logging.info(\"user name is: %s\", name)\n",
    "        name_list.append(name)\n",
    "        mobile = input(\"Please Give Your Mobile Number: \")\n",
    "        logging.info(\"user mobile number is: %s\", mobile)\n",
    "        name_list.append(mobile)\n",
    "        age = input(\"please Give Your Date of Birth: like dd/mm/yy \")\n",
    "        logging.info(\"user birth day date is: %s\", age)\n",
    "        name_list.append(age)\n",
    "\n",
    "        print(\"\\n\" + \"=\"*57 + \" Thank You \" + \"=\"*57)\n",
    "\n",
    "        print(f\"\"\"\n",
    "    Your Name is:          {name_list[0]}\n",
    "    Your Mobile Number is: {name_list[1]}\n",
    "    Your Date of Birth is: {name_list[2]}     \n",
    "        \"\"\") \n",
    "        ask = input(\"is everything correct? \")\n",
    "\n",
    "        if ask != \"yes\":\n",
    "            print(\"please try again\")\n",
    "        else:\n",
    "            print(\"Creating your Gameing ID \", end=\"\")\n",
    "            a = 0\n",
    "            while a<102:\n",
    "                print(\".\", end=\"\")\n",
    "                time.sleep(0.05)\n",
    "                a+=1\n",
    "            #return \" \"\n",
    "            print (\"\\n\\n\" + f\"Your Quiz Gameing ID is: {name_list[0][0] + name_list[1][1::2] + name_list[2][-4::1]}\")\n",
    "            \n",
    "            user_id =  name_list[0][0] + name_list[1][1::2] + name_list[2][-4::1]\n",
    "            \n",
    "            logging.info(\"user Quiz Gameing ID is: %s\", user_id)\n",
    "\n",
    "            time.sleep(2)\n",
    "            print(\"\\n\" + \"=\"*53 + \" Let's start the Game \" + \"=\"*52)\n",
    "\n",
    "            print(\"\"\"\n",
    "\n",
    "    Please Select the Subject 🙂\n",
    "\n",
    "    1. Science\n",
    "    2. Robotics\n",
    "    3. Math\n",
    "    4. Computer\n",
    "    5. Sports\n",
    "                \"\"\")\n",
    "            sub = input(\"please choose one: \").lower()\n",
    "            \n",
    "            logging.info(\"user choosed %s no subject\", sub)\n",
    "\n",
    "            if sub == \"1\" or sub == \"science\":\n",
    "                    print(\"\\n\"+\"=\"*47 + \" Thank you for selected Science \" + \"=\"*47)\n",
    "                    sleep_time()\n",
    "\n",
    "    #Question 1\n",
    "                    q1 = input(\"\"\"1. Which of the following is used in pencils?\n",
    "    a) Graphite\n",
    "    b) Silicon\n",
    "    c) Charcoal\n",
    "    d) Phosphorous\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q1}\")\n",
    "\n",
    "                    if q1 == \"a\" or q1 == \"graphite\":\n",
    "                        ok += 1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"1. Which of the following is used in pencils?\n",
    "    a) Graphite\n",
    "    b) Silicon\n",
    "    c) Charcoal\n",
    "    d) Phosphorous\n",
    "\n",
    "    Correct ans is:- a)Graphite\n",
    "    you gave: {q1}\n",
    "    \"\"\")\n",
    "\n",
    "    # Q2 for Science\n",
    "                    q2 = input(\"\"\"2. Chemical formula for water is\n",
    "    a) NaAlO2\n",
    "    b) H2O\n",
    "    c) Al2O3\n",
    "    d) CaSiO3\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q2}\")\n",
    "\n",
    "                    if q2 == \"b\" or q2 == \"h20\":\n",
    "                        ok += 1\n",
    "                    else:\n",
    "                        ng += 1\n",
    "                        wrong.append(f\"\"\"2. Chemical formula for water is\n",
    "    a) NaAlO2\n",
    "    b) H2O\n",
    "    c) Al2O3\n",
    "    d) CaSiO3\n",
    "\n",
    "    Correct ans is:- b)H2O\n",
    "    you gave: {q2}\n",
    "    \"\"\")\n",
    "\n",
    "    # Q3 for Science\n",
    "                    q3 = input(\"\"\"3. The gas usually filled in the electric bulb is\n",
    "    a) Nitrogen\n",
    "    b) Hydrogen\n",
    "    c) Carbon Dioxide\n",
    "    d) Oxygen\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q3}\")\n",
    "\n",
    "                    if q3 == \"a\" or q3 == \"nitrogen\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"3. The gas usually filled in the electric bulb is\n",
    "    a) Nitrogen\n",
    "    b) Hydrogen\n",
    "    c) Carbon Dioxide\n",
    "    d) Oxygen\n",
    "\n",
    "    Correct ans is:- a)Nitrogen\n",
    "    you gave: {q3}\n",
    "    \"\"\")\n",
    "\n",
    "    # Q4 for Science\n",
    "                    q4 = input(\"\"\"4. Which of the gas is not known as green house gas?\n",
    "    a) Methane\n",
    "    b) Nitrous oxide\n",
    "    c) Carbon dioxide\n",
    "    d) Hydrogen         \n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q4}\")\n",
    "\n",
    "                    if q4 == \"d\" or q4 == \"hydrogen\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"4. Which of the gas is not known as green house gas?\n",
    "    a) Methane\n",
    "    b) Nitrous oxide\n",
    "    c) Carbon dioxide\n",
    "    d) Hydrogen         \n",
    "\n",
    "    Correct ans is:- d)Hydrogen\n",
    "    you gave: {q4}\n",
    "    \"\"\")\n",
    "\n",
    "    # Q5 for Science\n",
    "                    q5 = input(\"\"\"5. Which of the following is used as a lubricant?\n",
    "    a) Graphite\n",
    "    b) Silica\n",
    "    c) Iron Oxide\n",
    "    d) Diamond           \n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q5}\")\n",
    "\n",
    "                    if q5 == \"a\" or q5 == \"graphite\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"5. Which of the following is used as a lubricant?\n",
    "    a) Graphite\n",
    "    b) Silica\n",
    "    c) Iron Oxide\n",
    "    d) Diamond           \n",
    "\n",
    "    Correct ans is:- a)Graphite\n",
    "    you gave: {q5}\n",
    "    \"\"\")\n",
    "            elif sub == \"2\" or sub == \"robotics\":\n",
    "                    print(\"\\n\" + \"=\"*47 + \" Thank you for selected Roborics \" + \"=\"*47)\n",
    "                    sleep_time()\n",
    "\n",
    "    #Q1 for robotics\n",
    "                    q1 = input(\"\"\"1. What is the full meaning of IR sensor?\n",
    "    a) infrared\n",
    "    b) infrared light\n",
    "    c) international radio\n",
    "    d) internet refollow\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q1}\")\n",
    "\n",
    "                    if q1 == \"a\" or q1 == \"infrared\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"1. What is the full meaning of IR sensor?\n",
    "    a) infrared\n",
    "    b) infrared light\n",
    "    c) international radio\n",
    "    d) internet refollow\n",
    "\n",
    "    Correct ans is:- a)infrared\n",
    "    you gave: {q1}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q2 for robotics\n",
    "                    q2 = input(\"\"\"2. What is the full meaning of PIR sensor?\n",
    "    a) positive infrared\n",
    "    b) point of infrared\n",
    "    c) Passive infrared\n",
    "    d) plus infrared \n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q2}\")\n",
    "\n",
    "                    if q2 == \"c\" or q2 == \"passive infrared\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"2. What is the full meaning of PIR sensor?\n",
    "    a) positive infrared\n",
    "    b) point of infrared\n",
    "    c) Passive infrared\n",
    "    d) plus infrared \n",
    "\n",
    "    Correct ans is:- c)Passive infrared\n",
    "    you gave: {q2}\n",
    "    \"\"\")\n",
    "\n",
    "    # Q3 for robotics\n",
    "                    q3 = input(\"\"\"3. What is the full meaning of RF?\n",
    "    a) Radio frequency\n",
    "    b) Radio free\n",
    "    c) Radio fall\n",
    "    d) Radio following\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q3}\")\n",
    "\n",
    "                    if q3 == \"a\" or q3 == \"radio frequency\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"3. What is the full meaning of RF?\n",
    "    a) Radio frequency\n",
    "    b) Radio free\n",
    "    c) Radio fall\n",
    "    d) Radio following\n",
    "\n",
    "    Correct ans is:- a)Radio frequency\n",
    "    you gave: {q3}\n",
    "    \"\"\")\n",
    "    # Q4 for robotics\n",
    "                    q4 = input(\"\"\"4. What is the full meaning of AI?\n",
    "    a) Artificial internet\n",
    "    b) Artificial information\n",
    "    c) Artificial interface\n",
    "    d) Artificial intelligence\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q4}\")\n",
    "\n",
    "                    if q4 == \"d\" or q4 == \"artificial intelligence\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"4. What is the full meaning of AI?\n",
    "    a) Artificial internet\n",
    "    b) Artificial information\n",
    "    c) Artificial interface\n",
    "    d) Artificial intelligence\n",
    "\n",
    "    Correct ans is:- d)Artificial intelligence\n",
    "    you gave: {q4}\n",
    "    \"\"\")\n",
    "\n",
    "    # Q5 for robotics\n",
    "                    q5 = input(\"\"\"5. what is the name of world best robot?\n",
    "    a) Reco            \n",
    "    b) Sophia\n",
    "    c) Roba\n",
    "    d) Seba\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q5}\")\n",
    "\n",
    "                    if q5 == \"b\" or q5 == \"sophia\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"5. what is the name of world best robot?\n",
    "    a) Reco            \n",
    "    b) Sophia\n",
    "    c) Roba\n",
    "    d) Seba\n",
    "\n",
    "    Correct ans is:- b)Sophia\n",
    "    you gave: {q5}\n",
    "    \"\"\")\n",
    "            elif sub == \"3\" or sub == \"math\":\n",
    "                    print(\"\\n\" + \"=\"*47 + \" Thank you for selected Math \" + \"=\"*47)\n",
    "                    sleep_time()\n",
    "\n",
    "    #Q1 for math\n",
    "                    q1 = input(\"\"\"1. Find the sum of 111 + 222 + 333\n",
    "    a) 700\n",
    "    b) 666\n",
    "    c) 10\n",
    "    d) 100\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q1}\")\n",
    "\n",
    "                    if q1 == \"b\" or q1 == \"666\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"1. Find the sum of 111 + 222 + 333\n",
    "    a) 700\n",
    "    b) 666\n",
    "    c) 10\n",
    "    d) 100\n",
    "\n",
    "    Correct ans is:- b)666\n",
    "    you gave: {q1}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q2 for math\n",
    "                    q2 = input(\"\"\"2. a = 10 & b = 5 then 2a+2b = ?\n",
    "    a) 20\n",
    "    b) 15\n",
    "    c) 30\n",
    "    d) 25\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q2}\")\n",
    "\n",
    "                    if q2 == \"c\" or q2 == \"30\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"2. a = 10 & b = 5 then 2a+2b = ?\n",
    "    a) 20\n",
    "    b) 15\n",
    "    c) 30\n",
    "    d) 25\n",
    "\n",
    "    Correct ans is:- c)30\n",
    "    you gave: {q2}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q3 for math\n",
    "                    q3 = input(\"\"\"3. a = 5 & b = 10 then (2a+2b)^2 = ?\n",
    "    a) 400\n",
    "    b) 150\n",
    "    c) 300\n",
    "    d) 900\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q3}\")\n",
    "\n",
    "                    if q3 == \"d\" or q3 == \"900\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"3. a = 5 & b = 10 then (2a+2b)^2 = ?\n",
    "    a) 400\n",
    "    b) 150\n",
    "    c) 300\n",
    "    d) 900\n",
    "\n",
    "    Correct ans is:- d)900\n",
    "    you gave: {q3}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q4 for math\n",
    "                    q4 = input(\"\"\"4. a = 5 & b = 10 then (2a-2b)^2 = ?\n",
    "    a) 100\n",
    "    b) 400\n",
    "    c) 800\n",
    "    d) 900\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q4}\")\n",
    "\n",
    "                    if q4 == \"a\" or q4 == \"100\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"4. a = 5 & b = 10 then (2a-2b)^2 = ?\n",
    "    a) 100\n",
    "    b) 400\n",
    "    c) 800\n",
    "    d) 900\n",
    "\n",
    "    Correct ans is:- a)100\n",
    "    you gave: {q4}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q5 for math\n",
    "                    q5 = input(\"\"\"5. a = 5 & b = 10 & c= 1 then (2a+2b+c)^2 = ?\n",
    "    a) 100\n",
    "    b) 300\n",
    "    c) 49\n",
    "    d) 900\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q5}\")\n",
    "\n",
    "                    if q5 == \"d\" or q5 == \"900\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"5. a = 5 & b = 10 & c= 1 then (2a+2b+c)^2 = ?\n",
    "    a) 100\n",
    "    b) 300\n",
    "    c) 49\n",
    "    d) 900\n",
    "\n",
    "    Correct ans is:- d)900\n",
    "    you gave: {q5}\n",
    "    \"\"\")\n",
    "            elif sub == \"4\" or sub == \"computer\":\n",
    "                    print(\"\\n\" + \"=\"*47 + \" Thank you for selected Computer \" + \"=\"*47)\n",
    "                    sleep_time()\n",
    "\n",
    "    #Q1 for computer\n",
    "                    q1 = input(\"\"\"1. When was the first computer invented?\n",
    "    a) 1945\n",
    "    b) 1943\n",
    "    c) 1918\n",
    "    d) 1937\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q1}\")\n",
    "\n",
    "                    if q1 == \"b\" or q1 == \"1943\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"1. When was the first computer invented?\n",
    "    a) 1945\n",
    "    b) 1943\n",
    "    c) 1918\n",
    "    d) 1937\n",
    "\n",
    "    Correct ans is:- b)1943\n",
    "    you gave: {q1}\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "    #Q2 for computer\n",
    "                    q2 = input(\"\"\"2. What was the name of the first computer invented?\n",
    "    a) ENIAC\n",
    "    b) ENI\n",
    "    c) ENCIA\n",
    "    d) ENICA\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q2}\")\n",
    "\n",
    "                    if q2 == \"a\" or q2 == \"eniac\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"2. What was the name of the first computer invented?\n",
    "    a) ENIAC\n",
    "    b) ENI\n",
    "    c) ENCIA\n",
    "    d) ENICA\n",
    "\n",
    "    Correct ans is:- a)ENIAC\n",
    "    you gave: {q2}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q3 for computer\n",
    "                    q3 = input(\"\"\"3. Who is known as the father of computers?\n",
    "    a) Pascal\n",
    "    b) Hollerith\n",
    "    c) Newman\n",
    "    d) Charles Babbage\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q3}\")\n",
    "\n",
    "                    if q3 == \"d\" or q3 == \"charles babbage\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"3. Who is known as the father of computers?\n",
    "    a) Pascal\n",
    "    b) Hollerith\n",
    "    c) Newman\n",
    "    d) Charles Babbage\n",
    "\n",
    "    Correct ans is:- d)Charles Babbage\n",
    "    you gave: {q3}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q4 for computer\n",
    "                    q4 = input(\"\"\"4. When was the first 1 GB disk drive released in the world?\n",
    "    a) 1980\n",
    "    b) 1970\n",
    "    c) 1981\n",
    "    d) 1971\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q4}\")\n",
    "\n",
    "                    if q4 == \"a\" or q4 == \"1980\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"4. When was the first 1 GB disk drive released in the world?\n",
    "    a) 1980\n",
    "    b) 1970\n",
    "    c) 1981\n",
    "    d) 1971\n",
    "\n",
    "    Correct ans is:- a)1980\n",
    "    you gave: {q4}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q5 for computer\n",
    "                    q5 = input(\"\"\"5. What was the name of the first computer programmer?\n",
    "    a) Alan Turing\n",
    "    b) Ada Lovelace\n",
    "    c) Tim Berners - Lee\n",
    "    d) Steve Wozniak\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q5}\")\n",
    "\n",
    "                    if q5 == \"b\" or q5 == \"ada lovelace\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"5. What was the name of the first computer programmer?\n",
    "    a) Alan Turing\n",
    "    b) Ada Lovelace\n",
    "    c) Tim Berners - Lee\n",
    "    d) Steve Wozniak\n",
    "\n",
    "    Correct ans is:- b)Ada Lovelace\n",
    "    you gave: {q5}\n",
    "    \"\"\")\n",
    "            elif sub == \"5\" or sub == \"Sports\":\n",
    "                    print(\"\\n\" + \"=\"*47 + \" Thank you for selected Sports \" + \"=\"*47)\n",
    "                    sleep_time()\n",
    "\n",
    "    #Q1 for sports\n",
    "                    q1 = input(\"\"\"1. Who is hosting the 2026 World Cup?\n",
    "    a) Canada\n",
    "    b) Mexico\n",
    "    c) United States\n",
    "    d) All of the Above\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q1}\")\n",
    "\n",
    "                    if q1 == \"d\" or q1 == \"all of the above\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"1. Who is hosting the 2026 World Cup?\n",
    "    a) Canada\n",
    "    b) Mexico\n",
    "    c) United States\n",
    "    d) All of the Above\n",
    "\n",
    "    Correct ans is:- d)All of the Above\n",
    "    you gave: {q1}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q2 for sports\n",
    "                    q2 = input(\"\"\"2. When was the first World Cup?\n",
    "    a) 1926\n",
    "    b) 1928\n",
    "    c) 1930\n",
    "    d) 1932\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q2}\")\n",
    "\n",
    "                    if q2 == \"c\" or q2 == \"1930\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"2. When was the first World Cup?\n",
    "    a) 1926\n",
    "    b) 1928\n",
    "    c) 1930\n",
    "    d) 1932\n",
    "\n",
    "    Correct ans is:- c)1930\n",
    "    you gave: {q2}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q3 for sports\n",
    "                    q3 = input(\"\"\"3. What does PK mean?\n",
    "    a) Pick'em\n",
    "    b) Point Known\n",
    "    c) Penalty Kick\n",
    "    d) Personal Knowledge\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q3}\")\n",
    "\n",
    "                    if q3 == \"a\" or q3 == \"pick'em\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"3. What does PK mean?\n",
    "    a) Pick'em\n",
    "    b) Point Known\n",
    "    c) Penalty Kick\n",
    "    d) Personal Knowledge\n",
    "\n",
    "    Correct ans is:- a)Pick'em\n",
    "    you gave: {q3}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q4 for sports\n",
    "                    q4 = input(\"\"\"4. Who has scored the most goals for the Brasil in World Cup history?\n",
    "    a) Neymar\n",
    "    b) Ronaldo\n",
    "    c) Pele\n",
    "    d) Zico\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q4}\")\n",
    "\n",
    "                    if q4 == \"c\" or q4 == \"pele\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"4. Who has scored the most goals for the Brasil in World Cup history?\n",
    "    a) Neymar\n",
    "    b) Ronaldo\n",
    "    c) Pele\n",
    "    d) Zico\n",
    "\n",
    "    Correct ans is:- c)Pele\n",
    "    you gave: {q4}\n",
    "    \"\"\")\n",
    "\n",
    "    #Q5 for sports\n",
    "                    q5 = input(\"\"\"5. Who is the richest player in the World Cup?\n",
    "    a) Kylian Mbappe, France\n",
    "    b) Cristiano Ronaldo, Portugal\n",
    "    c) Neymar Jr., Brazil\n",
    "    d) Lionel Messi, Argentina\n",
    "    \"\"\").lower()\n",
    "                    print(f\"You selected = {q5}\")\n",
    "\n",
    "                    if q5 == \"a\" or q5 == \"kylian mbappe, france\":\n",
    "                        ok +=1\n",
    "                    else:\n",
    "                        ng +=1\n",
    "                        wrong.append(f\"\"\"5. Who is the richest player in the World Cup?\n",
    "    a) Kylian Mbappe, France\n",
    "    b) Cristiano Ronaldo, Portugal\n",
    "    c) Neymar Jr., Brazil\n",
    "    d) Lionel Messi, Argentina\n",
    "\n",
    "    Correct ans is:- a)Kylian Mbappe, France\n",
    "    you gave: {q5}\n",
    "    \"\"\")\n",
    "            else:\n",
    "                    print(\"you are selected the wrong subject, please try again\")\n",
    "                    logging.info(\"user are selected wrong subject\")\n",
    "\n",
    "            if sub == \"1\" or sub == \"2\" or sub == \"3\" or sub == \"4\" or sub == \"5\":\n",
    "                result_ok = int((ok/5)*100)\n",
    "                result_ng = int((ng/5)*100)\n",
    "                if result_ok == 100:\n",
    "                    print (\"\\nCongratulations 😍\")\n",
    "                    print(f\"you gave {result_ok} % correct answers\")\n",
    "                    logging.info(f\"user gave {result_ok} % correct answers\")\n",
    "                elif result_ok > 50 and result_ok <100:\n",
    "                    print (\"\\nCongratulations 🙂\")\n",
    "                    print(f\"you gave {result_ok} % correct answers & {result_ng} % wrong answers\")\n",
    "                    logging.info(f\"user gave {result_ok} % correct answers\")\n",
    "                    logging.info(f\"user gave {result_ng} % wrong answers\")\n",
    "                else:\n",
    "                    print(\"\\n 😟😟😟\")\n",
    "                    print(f\"you gave {result_ok} % correct answers & {result_ng} % wrong answers\")\n",
    "                    logging.info(f\"user gave {result_ok} % correct answers\")\n",
    "                    logging.info(f\"user gave {result_ng} % wrong answers\")\n",
    "\n",
    "                if len(wrong) != 0:\n",
    "\n",
    "                    ask1 = input(\"are you want to see which question you gave the wrong answer to? \")\n",
    "                    if ask1 != \"yes\":\n",
    "                        logging.info(\"user aren't want to see worng answers\")\n",
    "                        pass\n",
    "                    else:\n",
    "                        logging.info(\"user want to see wrong answers\")\n",
    "                        for i in wrong:\n",
    "                            print(i)\n",
    "                            logging.info(\"%s\",i)\n",
    "                else:\n",
    "                    print(\"🙂🙂🙂\")\n",
    "\n",
    "                    \n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    logging.error(\"Error is happend\")\n",
    "    logging.exception(\"error is %s\",e)         "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d61d7646",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "celltoolbar": "Attachments",
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
